# Generated by Django 4.2.1 on 2023-08-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('category_slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug-URL for category')),
                ('category_img', models.ImageField(max_length=255, upload_to='C:\\Users\\gaming\\PycharmProjects\\test_Django_site_2\\test_project\\app1/media/app1/dir_for_CATEGORIES_IMAGES/', verbose_name='Изображение категории')),
                ('category_name', models.CharField(max_length=55, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_slug', models.SlugField(max_length=65, unique=True, verbose_name='Slug-URL for book')),
                ('book_img', models.ImageField(max_length=255, upload_to='C:\\Users\\gaming\\PycharmProjects\\test_Django_site_2\\test_project\\app1/media/app1/dir_for_BOOKS_IMAGES/', verbose_name='Изображение:')),
                ('current_price', models.IntegerField(verbose_name='Цена текущая(со скидкой):')),
                ('previous_price', models.IntegerField(blank=True, null=True, verbose_name='Цена без скидки:')),
                ('book_name', models.CharField(max_length=50, verbose_name='Название книги:')),
                ('book_genre', models.TextField(max_length=65, verbose_name='Жанр(ы):')),
                ('description', models.TextField(verbose_name='Описание книги:')),
                ('date_create', models.DateField(verbose_name='Дата издания книги:')),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category', verbose_name='Категория книги:')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
