# Generated by Django 4.2.1 on 2023-06-14 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\gaming\\PycharmProjects\\test_Django_site_2\\test_project\\app1/media/app1', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app1.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\gaming\\PycharmProjects\\test_Django_site_2\\test_project\\app1/media/app1', verbose_name='изображение'),
        ),
    ]
